language: python
python:
  - "3.5"
 # - "3.6-dev"  # 3.6 development branch
 # - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/test
# command to run tests
script:
#worked  - python test/SumTest.py
         - python -m unittest discover -s test/ -p "*Test.py"